# Generated by Django 5.0.7 on 2024-07-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='paid_until',
            field=models.DateField(default='9999-12-31'),
        ),
    ]
